FIXUP: Add missing include for Supplement
Fixes msvc build error without jumbo:

"error C2027: use of undefined type 'blink::LocalDOMWindow'"

Fixes: QTBUG-100544
Change-Id: Ie4dd68030452b50a221b04be2b4a3bdf78d4f41f
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>
Reviewed-by: Peter Varga <pvarga@inf.u-szeged.hu>