Fix not working optional for ViewActive
After switching to std::optional in
https://chromium-review.googlesource.com/c/chromium/src/+/4469528
history_item.cc stopped compiling at least with clang-cl as
'is_constructible_v<blink::HistoryItem::ViewState>'
was not satisfied. Do not use make_optional.

Deals with:
error: no matching function for call to 'make_optional'

Change-Id: I86981eb13ead7a360bb00db7e653558ba3e95dcd
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/558488
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>