Work-around linker error on armv7
We get undefined reference to kNoCropRect in
CropRect(const SkIRect* optionalCrop), so instead use
CropRect(const SkIRect& crop), since the pointer isn't nullable
anyway.

Change-Id: Id02deec1c57abd8d34fda70673c5973626000e96
Reviewed-by: Peter Varga <pvarga@inf.u-szeged.hu>