[backport] Guard conflicting pthread_mutexattr_setprotocol with IS_ANDROID
Newer versions of glibc provide a different declaration
causing a build error.

../../base/synchronization/lock_impl_posix.cc:26:27: error: conflicting declaration of C function ‘int pthread_mutexattr_setprotocol(pthread_mutexattr_t*)’
   26 | int __attribute__((weak)) pthread_mutexattr_setprotocol(
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/15/x86_64-suse-linux/bits/gthr-default.h:35,
                 from /usr/include/c++/15/x86_64-suse-linux/bits/gthr.h:157,
                 from /usr/include/c++/15/ext/atomicity.h:37,
                 from /usr/include/c++/15/bits/ios_base.h:41,
                 from /usr/include/c++/15/ios:46,
                 from /usr/include/c++/15/bits/ostream.h:43,
                 from /usr/include/c++/15/bits/unique_ptr.h:43,
                 from /usr/include/c++/15/memory:80,
                 from ../../base/check.h:9,
                 from ../../base/synchronization/lock_impl.h:11,
                 from ../../base/synchronization/lock_impl_posix.cc:5:
/usr/include/pthread.h:913:12: note: previous declaration ‘int pthread_mutexattr_setprotocol(pthread_mutexattr_t*, int)’
  913 | extern int pthread_mutexattr_setprotocol (pthread_mutexattr_t *__attr,
      |

Review-URL: https://chromium-review.googlesource.com/c/chromium/src/+/6921906
Cr-Commit-Position: refs/heads/main@{#1516010}
Change-Id: Iab43268f1a36ff4dc3b5b98283902a1f8b7eb5c4
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/694185
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>