abseil-cpp: fix build with glibc-2.34
Backport upstream fix for:
 ../../../../../git/src/3rdparty/chromium/third_party/abseil-cpp/absl/debugging/failure_signal_handler.cc: In function 'bool absl::SetupAlternateStackOnce()':
 ../../../../../git/src/3rdparty/chromium/third_party/abseil-cpp/absl/debugging/failure_signal_handler.cc:139:32: error: no matching function for call to 'max(long int, int)'
   size_t stack_size = (std::max(SIGSTKSZ, 65536) + page_mask) & ~page_mask;
                        ~~~~~~~~^~~~~~~~~~~~~~~~~

Caused by SIGSTCKZ no longer being compile time constant in glibc-2.34.

https://github.com/abseil/abseil-cpp/commit/a9831f1cbf93fb18dd951453635f488037454ce9

Change-Id: I88611684c25ffbc9d8a27a02ca55b906098b48a8
Reviewed-by: Michal Klocek <michal.klocek@qt.io>