Fix missing dependency for qtwebengine/browser/pdf
From time to time with extensions build on we get:
chromium/qtwebengine/browser/pdf/pdf_extension_util.cc:49:10:
  fatal error: 'chrome/grit/generated_resources.h' file not found

Add missing dependency.

Change-Id: Idf73253da7a1cda3b358d4e5fac7c593085695dc
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>