[backport] libstdc++: Add initializers for constexpr static data members in Node
In the CL https://crrev.com/c/6512733 static constexpr data members of
structs ParentNodeTag and ShadowHostTag were added without initializers.
But C++ standard requires initializer for constexpr static data member
of LiteralType. So, added missing initializers for these structs.

Without this change the build fails with GCC compiler errors like:
../../third_party/blink/renderer/core/dom/node.h:1261:5: error: 'constexpr' static data member 'kParentNodeTag' must have an initializer

Bug: 41455655
Review-URL: https://chromium-review.googlesource.com/c/chromium/src/+/6867590
Cr-Commit-Position: refs/heads/main@{#1505983}
Change-Id: I36e33cb895a26f1431589f339acf26fbdf880950
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/691690
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>