[sandbox] Fix build with glibc-2.43 and above
Fixes error:
//sandbox/linux/system_headers/linux_seccomp.h:218:39: error: expected identifier before numeric constant
  218 | #define SYS_SECCOMP                   1
      |                                       ^
error: expected ‘}’ before numeric constant

See https://crbug.com/456218403

Change-Id: I5f2ea6826650b9eff6b4defff694f24e301f7663
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/713181
Reviewed-by: Moss Heim <moss.heim@qt.io>
(cherry picked from commit bf8bd5512920b28468d99b9ce550f0617e57d7f4)
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/713447
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>