Fix windows build with newest compiler
Newest msvc 17.9.5 has issue when compiling distributed_point_function
and fails with:
"fatal error C1002: compiler is out of heap space in pass 2"

Unfortunately cl compiler is close source so there is no way to instrument the code and see what exactly goes wrong.

As a fix roll the highway project to 118-based, which make distributed_point_function buildable on windows, however introduces issues for older gcc compiler. Luckily the issue has already
workaround in follw-up patch.

Note 4GB memory peek is expected when compiling evaluate_prg_hwy.cc.

Fixes: QTBUG-123822
Change-Id: I99be8eef6bf8fb6fcc43f322208e6dd25e0ae1e0
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/553655
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>