[fixup] Adapt autofill component for WebEngine
Fix build race condition due to missing dep, dells with:

In file included from ... autofill/core/browser/autofill_field.h:21,
                 from ... autofill/core/browser/autofill_type.cc:11:
... autofill/core/browser/form_parsing/regex_patterns.h:14:10:
fatal error: components/autofill/core/browser/form_parsing/buildflags.h: No such file or directory

Change-Id: I6fc657542891aeaaf12f940381c251aba0273d5d
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/600653
Reviewed-by: Peter Varga <pvarga@inf.u-szeged.hu>
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>