[fixup] Adapt autofill component for WebEngine
Yet another build fix for race condition due to missing dep:

... autofill/core/browser/autofill_manager.cc:30:10:
fatal error: components/optimization_guide/machine_learning_tflite_buildflags.h: No such file or directory

Change-Id: I5e7bdd2c6b80e6c2d63603cb9bb77ebbab1e8fce
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/600807
Reviewed-by: Michal Klocek <michal.klocek@qt.io>