Workaround for linker error on macOS after 67-based
The linker error is:
  Undefined symbols for architecture x86_64:
    "fxcrt::StringViewTemplate<char>::operator=(fxcrt::StringViewTemplate<char> const&)", referenced from:
        (anonymous namespace)::SplitQualifiedName(fxcrt::StringViewTemplate<char> const&, fxcrt::StringViewTemplate<char>*, fxcrt::StringViewTemplate<char>*) in libfxcrt.a(cxml_element.o)
        (anonymous namespace)::ReplaceAbbr(CPDF_Object*) in libfpdfapi.a(cpdf_streamconte)
        CPDF_ToUnicodeMap::Load(CPDF_Stream*) in libfpdfapi.a(cpdf_tounicodema)
  ld: symbol(s) not found for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)

The symbol seems to be dropped by clang, probably because it is unused
in bytestring.cpp. As a workaround, instantiate the template where it is
used.

Change-Id: I45601f28b95f17e6135ebbe3a4582ba93f6f4985
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>