[fixup][msvc] Fix QtWebEngine build on Windows
Fix template argument mismatch and use the same explicitly-qualified
form as the definition

For generated template:

template<int STATE>
    class DeepSerializedValueBuilder {
    public:
        enum {
            NoFieldsSet = 0,
            TypeSet = 1 << 1,
            AllFieldsSet = (TypeSet | 0)};
   ...
   }

Change type setter form:

DeepSerializedValueBuilder<STATE | TypeSet>& SetType(const String&
value);

to:

DeepSerializedValueBuilder<STATE |
DeepSerializedValueBuilder<STATE>::TypeSet>& SetType(const String&
value);

Deals with:

..../content/browser/devtools/protocol/runtime.h(987): error C2244:
'content::protocol::Runtime::DeepSerializedValue::DeepSerializedValueBuilder<STATE>::SetType':
unable to match function definition to an existing declaration

Change-Id: Ia951b4240dab156d3679eec8c9a862cb414f18b3
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/748563
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>
(cherry picked from commit 10236088e164d53bb4b5fb7230471b01b744fbdd)
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/753551
Reviewed-by: Kaloyan Chehlarski <kaloyan.chehlarski@qt.io>