breakpad: fix build with glibc-2.34
Fix compilation error:
../../../../git/src/3rdparty/chromium/third_party/breakpad/breakpad/src/client/linux/handler/exception_handler.cc:141:49: error: no matching function for call to 'max(int, long int)'
  141 |   static const unsigned kSigStackSize = std::max(16384, SIGSTKSZ);
      |                                         ~~~~~~~~^~~~~~~~~~~~~~~~~

Caused by SIGSTCKZ no longer being compile time constant in glibc-2.34.

Change-Id: I19e6f848208144e6d2abfa36e5a62edf28f0bfd4
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>