Fix compilation in ci with lastest security patches
Add missing header.

Deals with:
"blink/renderer/core/workers/worker_thread.cc:301:28:
error: 'kWorkerThreadSequentialShutdown' is not a member of 'blink::features'"

Change-Id: Ic85ea4329c6c82c59044b2d8e8033913823148aa
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/658191
Reviewed-by: Michael Brüning <michael.bruning@qt.io>
(cherry picked from commit 9238ccbccf31c8a7bba5e2e2f99639634d8476b1)
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/658610
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>