[Backport] [PA] Uninline sentinel slot span
This change partially undoes https://crrev.com/c/3412485, in which the
sentinel slot span was marked `inline` at its declaration inside
`SlotSpanMetadata`. This is needed to build under MSVC, which otherwise
immediately spits out

```
partition_page.h(313): error C2512:
  'partition_alloc::internal::SlotSpanMetadata<true>': no appropriate
  default constructor available
partition_bucket.h(29): note: see declaration of
  'partition_alloc::internal::SlotSpanMetadata<true>'
partition_page.h(327): note: see reference to class template
  instantiation 'partition_alloc::internal::SlotSpanMetadata<true>'
  being compiled
```

Bug: 1351310
Change-Id: I2b419c978206ce9c2786826f9ff39bf9a5fcf7ed
Review-URL: https://chromium-review.googlesource.com/c/chromium/src/+/3858985
Cr-Commit-Position: refs/heads/main@{#1039664}
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/443564
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>