[Backport] Fix missing cmath header build failure in renderer extension
Building 106.0.5249.51 on a Debian machine, I hit the following
build error:

FAILED: obj/extensions/renderer/renderer/argument_spec.o
clang++ [...] -o obj/extensions/renderer/renderer/argument_spec.o
../../extensions/renderer/bindings/argument_spec.cc:410:16: error: no member named 'isnan' in namespace 'std'
      if (std::isnan(double_val) || std::isinf(double_val)) {
          ~~~~~^
../../extensions/renderer/bindings/argument_spec.cc:410:42: error: no member named 'isinf' in namespace 'std'
      if (std::isnan(double_val) || std::isinf(double_val)) {
                                    ~~~~~^
2 errors generated.

isnan and isinf are both found in the cmath header, so simply
including it fixes that build error.

Change-Id: I5c266c663d80e5d40a11f0d0e8b63ee5aaacf7ea
Review-URL: https://chromium-review.googlesource.com/c/chromium/src/+/3913616
Cr-Commit-Position: refs/heads/main@{#1052196}
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/442872
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>