Fix build with clang
Use neon inntrinsics

Fixes

| ../../../../../git/src/3rdparty/chromium/third_party/skia/src/opts/SkRasterPipeline_opts.h:1030:19: error: functional-style cast from 'F' (aka 'V<float>') to '__fp16' is not allowed
|     __fp16 fp16 = __fp16(f);
|                   ^~~~~~~~

Upstream Skia has fixed it differently

Change-Id: I1f2461753ca2754b84bc5de4c2167c7f8c42a64c
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/487065
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>
(cherry picked from commit 98f2bdca0511e84f9ed5484b3c982f60899b1cbd)
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/500439
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>