[backport] Fix intrinsic use in Skia
This is a squashed backport of 3 cherry-picked commits from
https://skia.googlesource.com/skcms.git. Together they fix the build
for clang 22:

```
../../../../../qt6/qtwebengine/src/3rdparty/chromium/third_party/skia/modules/skcms/src/Transform_inl.h:165:12: error: use of undeclared identifier '__builtin_ia32_vcvtph2ps256'; did you mean '__builtin_ia32_cvtpd2ps256'?
  165 |     return __builtin_ia32_vcvtph2ps256((I16)half);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            __builtin_ia32_cvtpd2ps256
```

-

Change use of removed intrinsic

A recent LLVM change removed the __builtin_ia32_vcvtph2ps256 intrinsic
because it can be implemented using __builtin_shufflevector and/or
__builtin_convertvector. This CL changes skia to use convertvector as
to match.

https://skia-review.googlesource.com/c/skcms/+/1038217

-

Gate F_From_Half change on clang

It seems like gcc doesn't support the _Float16 type, which clang
needs to use to make casting work, so only use
__builtin_convertvector when building with clang.

https://skia-review.googlesource.com/c/skcms/+/1040717

-

Guard _Float16 use on clang >= 15

https://skia-review.googlesource.com/c/skcms/+/1041596

Change-Id: I827f9f706c3d0224c714fe80d0ae5f8274fecae3
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/729570
Reviewed-by: Michal Klocek <michal.klocek@qt.io>
(cherry picked from commit e2d827472a4960fd763a419e634db59c7fecfb5d)
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/729911
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>