[fixup][backport] CVE-2025-6021
Add missing header. Delas with:
"tree.c:187:17: error: ‘SIZE_MAX’ undeclared"

Change-Id: I9238973d2d231cb7d128ecd2d3aedd735dafe3cd
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/690020
Reviewed-by: Moss Heim <moss.heim@qt.io>