[fixup] Fix QtWebEngine build on all platforms
Fix clang-21 build with UMA macros

clang-21 doesn't like this because it requires an enum value outside the
valid enumeration range in a constant expression. Just remove the macros
since we don't make use of this.

Fixes the following:

```
error: static assertion expression is not an integral constant expression
note: expanded from macro 'UMA_HISTOGRAM_ENUMERATION'
[...]
note: integer value 4 is outside the valid range of values [0, 3] for the enumeration type 'LandlockState'
```

Change-Id: Id5664e8feb31158392b2ab792f22b1358493e5cb
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/688835
Reviewed-by: Michael Brüning <michael.bruning@qt.io>