[Backport] IWYU: include blink::URLLoader for unique_ptr usage in WebLocalFrameClient
Recent refactor broke again libstdc++ build by not including URLLoader
header. But the reason for that change was removing in public code
includes of non public code, as URLLoader.

To fix the problem, move the implementation exposing the problem
to the .cc file.

Fixes build error with libstdc++:
    /usr/include/c++/12/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = blink::URLLoader]’:
    /usr/include/c++/12/bits/unique_ptr.h:396:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = blink::URLLoader; _Dp = std::default_delete<blink::URLLoader>]’
    ../../third_party/blink/public/web/web_local_frame_client.h:678:12:   required from here
    /usr/include/c++/12/bits/unique_ptr.h:93:23: error: invalid application of ‘sizeof’ to incomplete type ‘blink::URLLoader’

Bug: 957519
Change-Id: I77a2a97865255b8e3a1044e8040d5c850f9023aa
Review-URL: https://chromium-review.googlesource.com/c/chromium/src/+/4276241
Cr-Commit-Position: refs/heads/main@{#1111077}
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/481385
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>