[backport] win: Add missing <limits> include
Fixes the following error when building on Windows with
`use_custom_libcxx=false`:

oom.cc(52,36): error: no member named 'numeric_limits' in namespace 'std'
   52 |   constexpr size_t kInvalid = std::numeric_limits<ULONG_PTR>::max();
      |                               ~~~~~^

Change-Id: I7ed6efe848164bf079c564aae311550f327720fb
Review-URL: https://chromium-review.googlesource.com/c/chromium/src/+/5891459
Cr-Commit-Position: refs/heads/main@{#1360693}
Reviewed-on: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/612257
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>