Suppress conversion errors with MSVC 2015 64 bit
Suppresses following fatal warnings:

chromium\v8\src\base\platform\platform-win32.cc(1136): error C2220: warning treated as error - no 'object' file generated
chromium\v8\src\base\platform\platform-win32.cc(1136): warning C4311: 'reinterpret_cast': pointer truncation from 'BYTE *' to 'unsigned int'
v8\src\base\platform\platform-win32.cc(1136): warning C4302: 'reinterpret_cast': truncation from 'BYTE *' to 'unsigned int'
chromium\v8\src\base\platform\platform-win32.cc(1138): warning C4311: 'reinterpret_cast': pointer truncation from 'BYTE *' to 'unsigned int'
chromium\v8\src\base\platform\platform-win32.cc(1138): warning C4302: 'reinterpret_cast': truncation from 'BYTE *' to 'unsigned int'

and

chromium\third_party\leveldatabase\src\db\skiplist.h(360): warning C4312:
'reinterpret_cast': conversion from 'int' to 'void *' of greater size

Conflicts:
	chromium/build/common.gypi

Reviewed-by: Michael Brüning <michael.bruning@theqtcompany.com>
Change-Id: Ie6a5b0728011702e20428b3a55deef5a925ac2d6
Reviewed-by: Joerg Bornemann <joerg.bornemann@theqtcompany.com>